### ISSUE TITLE
build fail, When a model has a property named type

### ISSUE THREAD

**Issue by hanshantao** [winddpan/CodableWrapper#22] opened 2024-02-01 02:19 UTC
Reproduce sample code:

@Codable
class Foo: Codable {
    var bar: String? = ""
    var type: String = ""
}

when build xcode error message: 
Use of 'type' refers to instance method rather than global function 'type(of:)' in module 'Swift'

**Comment by winddpan** [comment] 2024-02-01 02:28
What is your Xcode and Swift version? I will try a test.

**Comment by hanshantao** [comment] 2024-02-01 02:44
Xcode 15.2 Swift 5.9

**Comment by winddpan** [comment] 2024-02-01 02:50
My environment is the same, but I can't reproduce this issue, can you provide a MVP demo?

**Comment by hanshantao** [comment] 2024-02-01 03:02
ok
[ReproDemo.zip](https://github.com/winddpan/CodableWrapper/files/14119722/ReproDemo.zip)
Another problem, when comments and code are on the same line, swift macro resolution gets stuck. 
But It's swift marco bugs, swift issues https://github.com/apple/swift/issues/69962

**Comment by winddpan** [comment] 2024-02-01 05:23
fixed in 1.0.3

**Closed** 2024-02-01 05:32 UTC
